### ISSUE TITLE
「/」には、SI単位系で使用できない文字が含まれています

### ISSUE THREAD

**Issue by tueda** [kn1cht/textlint-rule-use-si-units#2]
READMEやテストケースからは既知なのか判断できなかったので報告させていただきますが、「半角スペース」+「半角スラッシュ」の組み合わせがすべて表題のメッセージとともにエラーとなります。

![image](https://user-images.githubusercontent.com/1481665/106870257-3d46f780-6714-11eb-8179-b405bf012621.png)

なお、上の画像のようにLaTeXの数式モードなどでスペースが無視される場合は、単純にスペースを削除することがワークアラウンドとなります。

**Comment by kn1cht** [comment]
@tueda ご報告ありがとうございます。
スラッシュについては `m/s` のように単位記号と組み合わせて使われることから単位と判定されていますが、スラッシュ単体を単位として使う人はいないと思われるので、警告されないように修正致します。

**Comment by kn1cht** [comment]
@tueda マッチ文字列が記号だけ（`'^/·･・()'`）で構成されている場合を例外として、エラーを出さないように修正しました。
`v1.0.2`として公開してありますのでお試しくださいませ。

**Comment by tueda** [comment]
@kn1cht 修正ありがとうございます。エラーが出ないことを確認いたしました。
